DROP TABLE TRANSACTION;
DROP TABLE NOTIFICATION;
DROP TABLE BOOKING;
DROP TABLE BOOKINGREQUEST;
DROP TABLE LISTING;
DROP TABLE CAROWNER;
DROP TABLE CARRENTER;
DROP TABLE USER;


DROP TABLE CREDITCARD ;
DROP TABLE DRIVERLICENSE;
DROP TABLE REGO;
DROP TABLE CARPRICE;