DROP TRIGGER after_carowner_insert;
DROP TABLE MESSAGE;
DROP TABLE TRANSACTION;
DROP TABLE NOTIFICATION;
DROP TABLE BOOKING;
DROP TABLE BOOKINGREQUEST;
DROP TABLE AVAILABILITY;
DROP TABLE LISTING;
DROP TABLE CAR;
DROP TABLE CAROWNER;
DROP TABLE CARRENTER;
DROP TABLE USER;


DROP TABLE CREDITCARD ;
DROP TABLE DRIVERLICENSE;
DROP TABLE REGO;
DROP TABLE CARPRICE;
DROP TABLE BANKACCOUNT;